
#ifndef _CTP_STRUCT_
#define _CTP_STRUCT_

#include <node.h>

#define MSG_MAX_COUNT 200

//////////////// Request Function Callback Enum
#define T_CONNECT 1
#define T_REQAUTHENTICATE 2
#define T_REQUSERLOGIN 3
#define T_REQUSERLOGOUT 4
#define T_REQUSERPASSWORDUPDATE 5
#define T_REQTRADINGACCOUNTPASSWORDUPDATE 6
#define T_REQORDERINSERT 7
#define T_REQPARKEDORDERINSERT 8
#define T_REQPARKEDORDERACTION 9
#define T_REQORDERACTION 10
#define T_REQQUERYMAXORDERVOLUME 11
#define T_REQSETTLEMENTINFOCONFIRM 12
#define T_REQREMOVEPARKEDORDER 13
#define T_REQREMOVEPARKEDORDERACTION 14
#define T_REQEXECORDERINSERT 15
#define T_REQEXECORDERACTION 16
#define T_REQFORQUOTEINSERT 17
#define T_REQQUOTEINSERT 18
#define T_REQQUOTEACTION 19
#define T_REQBATCHORDERACTION 20
#define T_REQOPTIONSELFCLOSEINSERT 21
#define T_REQOPTIONSELFCLOSEACTION 22
#define T_REQCOMBACTIONINSERT 23
#define T_REQQRYORDER 24
#define T_REQQRYTRADE 25
#define T_REQQRYINVESTORPOSITION 26
#define T_REQQRYTRADINGACCOUNT 27
#define T_REQQRYINVESTOR 28
#define T_REQQRYTRADINGCODE 29
#define T_REQQRYINSTRUMENTMARGINRATE 30
#define T_REQQRYINSTRUMENTCOMMISSIONRATE 31
#define T_REQQRYEXCHANGE 32
#define T_REQQRYPRODUCT 33
#define T_REQQRYINSTRUMENT 34
#define T_REQQRYDEPTHMARKETDATA 35
#define T_REQQRYSETTLEMENTINFO 36
#define T_REQQRYTRANSFERBANK 37
#define T_REQQRYINVESTORPOSITIONDETAIL 38
#define T_REQQRYNOTICE 39
#define T_REQQRYSETTLEMENTINFOCONFIRM 40
#define T_REQQRYINVESTORPOSITIONCOMBINEDETAIL 41
#define T_REQQRYCFMMCTRADINGACCOUNTKEY 42
#define T_REQQRYEWARRANTOFFSET 43
#define T_REQQRYINVESTORPRODUCTGROUPMARGIN 44
#define T_REQQRYEXCHANGEMARGINRATE 45
#define T_REQQRYEXCHANGEMARGINRATEADJUST 46
#define T_REQQRYEXCHANGERATE 47
#define T_REQQRYSECAGENTACIDMAP 48
#define T_REQQRYPRODUCTEXCHRATE 49
#define T_REQQRYPRODUCTGROUP 50
#define T_REQQRYMMINSTRUMENTCOMMISSIONRATE 51
#define T_REQQRYMMOPTIONINSTRCOMMRATE 52
#define T_REQQRYINSTRUMENTORDERCOMMRATE 53
#define T_REQQRYSECAGENTTRADINGACCOUNT 54
#define T_REQQRYSECAGENTCHECKMODE 55
#define T_REQQRYOPTIONINSTRTRADECOST 56
#define T_REQQRYOPTIONINSTRCOMMRATE 57
#define T_REQQRYEXECORDER 58
#define T_REQQRYFORQUOTE 59
#define T_REQQRYQUOTE 60
#define T_REQQRYOPTIONSELFCLOSE 61
#define T_REQQRYINVESTUNIT 62
#define T_REQQRYCOMBINSTRUMENTGUARD 63
#define T_REQQRYCOMBACTION 64
#define T_REQQRYTRANSFERSERIAL 65
#define T_REQQRYACCOUNTREGISTER 66
#define T_REQQRYCONTRACTBANK 67
#define T_REQQRYPARKEDORDER 68
#define T_REQQRYPARKEDORDERACTION 69
#define T_REQQRYTRADINGNOTICE 70
#define T_REQQRYBROKERTRADINGPARAMS 71
#define T_REQQRYBROKERTRADINGALGOS 72
#define T_REQQUERYCFMMCTRADINGACCOUNTTOKEN 73
#define T_REQFROMBANKTOFUTUREBYFUTURE 74
#define T_REQFROMFUTURETOBANKBYFUTURE 75
#define T_REQQUERYBANKACCOUNTMONEYBYFUTURE 76

//////////////// Response Function Callback Enum
#define T_ONFRONTCONNECTED 77
#define T_ONFRONTDISCONNECTED 78
#define T_ONHEARTBEATWARNING 79
#define T_ONRSPAUTHENTICATE 80
#define T_ONRSPUSERLOGIN 81
#define T_ONRSPUSERLOGOUT 82
#define T_ONRSPUSERPASSWORDUPDATE 83
#define T_ONRSPTRADINGACCOUNTPASSWORDUPDATE 84
#define T_ONRSPORDERINSERT 85
#define T_ONRSPPARKEDORDERINSERT 86
#define T_ONRSPPARKEDORDERACTION 87
#define T_ONRSPORDERACTION 88
#define T_ONRSPQUERYMAXORDERVOLUME 89
#define T_ONRSPSETTLEMENTINFOCONFIRM 90
#define T_ONRSPREMOVEPARKEDORDER 91
#define T_ONRSPREMOVEPARKEDORDERACTION 92
#define T_ONRSPEXECORDERINSERT 93
#define T_ONRSPEXECORDERACTION 94
#define T_ONRSPFORQUOTEINSERT 95
#define T_ONRSPQUOTEINSERT 96
#define T_ONRSPQUOTEACTION 97
#define T_ONRSPBATCHORDERACTION 98
#define T_ONRSPOPTIONSELFCLOSEINSERT 99
#define T_ONRSPOPTIONSELFCLOSEACTION 100
#define T_ONRSPCOMBACTIONINSERT 101
#define T_ONRSPQRYORDER 102
#define T_ONRSPQRYTRADE 103
#define T_ONRSPQRYINVESTORPOSITION 104
#define T_ONRSPQRYTRADINGACCOUNT 105
#define T_ONRSPQRYINVESTOR 106
#define T_ONRSPQRYTRADINGCODE 107
#define T_ONRSPQRYINSTRUMENTMARGINRATE 108
#define T_ONRSPQRYINSTRUMENTCOMMISSIONRATE 109
#define T_ONRSPQRYEXCHANGE 110
#define T_ONRSPQRYPRODUCT 111
#define T_ONRSPQRYINSTRUMENT 112
#define T_ONRSPQRYDEPTHMARKETDATA 113
#define T_ONRSPQRYSETTLEMENTINFO 114
#define T_ONRSPQRYTRANSFERBANK 115
#define T_ONRSPQRYINVESTORPOSITIONDETAIL 116
#define T_ONRSPQRYNOTICE 117
#define T_ONRSPQRYSETTLEMENTINFOCONFIRM 118
#define T_ONRSPQRYINVESTORPOSITIONCOMBINEDETAIL 119
#define T_ONRSPQRYCFMMCTRADINGACCOUNTKEY 120
#define T_ONRSPQRYEWARRANTOFFSET 121
#define T_ONRSPQRYINVESTORPRODUCTGROUPMARGIN 122
#define T_ONRSPQRYEXCHANGEMARGINRATE 123
#define T_ONRSPQRYEXCHANGEMARGINRATEADJUST 124
#define T_ONRSPQRYEXCHANGERATE 125
#define T_ONRSPQRYSECAGENTACIDMAP 126
#define T_ONRSPQRYPRODUCTEXCHRATE 127
#define T_ONRSPQRYPRODUCTGROUP 128
#define T_ONRSPQRYMMINSTRUMENTCOMMISSIONRATE 129
#define T_ONRSPQRYMMOPTIONINSTRCOMMRATE 130
#define T_ONRSPQRYINSTRUMENTORDERCOMMRATE 131
#define T_ONRSPQRYSECAGENTTRADINGACCOUNT 132
#define T_ONRSPQRYSECAGENTCHECKMODE 133
#define T_ONRSPQRYOPTIONINSTRTRADECOST 134
#define T_ONRSPQRYOPTIONINSTRCOMMRATE 135
#define T_ONRSPQRYEXECORDER 136
#define T_ONRSPQRYFORQUOTE 137
#define T_ONRSPQRYQUOTE 138
#define T_ONRSPQRYOPTIONSELFCLOSE 139
#define T_ONRSPQRYINVESTUNIT 140
#define T_ONRSPQRYCOMBINSTRUMENTGUARD 141
#define T_ONRSPQRYCOMBACTION 142
#define T_ONRSPQRYTRANSFERSERIAL 143
#define T_ONRSPQRYACCOUNTREGISTER 144
#define T_ONRSPERROR 145
#define T_ONRTNORDER 146
#define T_ONRTNTRADE 147
#define T_ONERRRTNORDERINSERT 148
#define T_ONERRRTNORDERACTION 149
#define T_ONRTNINSTRUMENTSTATUS 150
#define T_ONRTNBULLETIN 151
#define T_ONRTNTRADINGNOTICE 152
#define T_ONRTNERRORCONDITIONALORDER 153
#define T_ONRTNEXECORDER 154
#define T_ONERRRTNEXECORDERINSERT 155
#define T_ONERRRTNEXECORDERACTION 156
#define T_ONERRRTNFORQUOTEINSERT 157
#define T_ONRTNQUOTE 158
#define T_ONERRRTNQUOTEINSERT 159
#define T_ONERRRTNQUOTEACTION 160
#define T_ONRTNFORQUOTERSP 161
#define T_ONRTNCFMMCTRADINGACCOUNTTOKEN 162
#define T_ONERRRTNBATCHORDERACTION 163
#define T_ONRTNOPTIONSELFCLOSE 164
#define T_ONERRRTNOPTIONSELFCLOSEINSERT 165
#define T_ONERRRTNOPTIONSELFCLOSEACTION 166
#define T_ONRTNCOMBACTION 167
#define T_ONERRRTNCOMBACTIONINSERT 168
#define T_ONRSPQRYCONTRACTBANK 169
#define T_ONRSPQRYPARKEDORDER 170
#define T_ONRSPQRYPARKEDORDERACTION 171
#define T_ONRSPQRYTRADINGNOTICE 172
#define T_ONRSPQRYBROKERTRADINGPARAMS 173
#define T_ONRSPQRYBROKERTRADINGALGOS 174
#define T_ONRSPQUERYCFMMCTRADINGACCOUNTTOKEN 175
#define T_ONRTNFROMBANKTOFUTUREBYBANK 176
#define T_ONRTNFROMFUTURETOBANKBYBANK 177
#define T_ONRTNREPEALFROMBANKTOFUTUREBYBANK 178
#define T_ONRTNREPEALFROMFUTURETOBANKBYBANK 179
#define T_ONRTNFROMBANKTOFUTUREBYFUTURE 180
#define T_ONRTNFROMFUTURETOBANKBYFUTURE 181
#define T_ONRTNREPEALFROMBANKTOFUTUREBYFUTUREMANUAL 182
#define T_ONRTNREPEALFROMFUTURETOBANKBYFUTUREMANUAL 183
#define T_ONRTNQUERYBANKBALANCEBYFUTURE 184
#define T_ONERRRTNBANKTOFUTUREBYFUTURE 185
#define T_ONERRRTNFUTURETOBANKBYFUTURE 186
#define T_ONERRRTNREPEALBANKTOFUTUREBYFUTUREMANUAL 187
#define T_ONERRRTNREPEALFUTURETOBANKBYFUTUREMANUAL 188
#define T_ONERRRTNQUERYBANKBALANCEBYFUTURE 189
#define T_ONRTNREPEALFROMBANKTOFUTUREBYFUTURE 190
#define T_ONRTNREPEALFROMFUTURETOBANKBYFUTURE 191
#define T_ONRSPFROMBANKTOFUTUREBYFUTURE 192
#define T_ONRSPFROMFUTURETOBANKBYFUTURE 193
#define T_ONRSPQUERYBANKACCOUNTMONEYBYFUTURE 194
#define T_ONRTNOPENACCOUNTBYBANK 195
#define T_ONRTNCANCELACCOUNTBYBANK 196
#define T_ONRTNCHANGEACCOUNTBYBANK 197
#define T_SUBSCRIBEMARKETDATA 198
#define T_UNSUBSCRIBEMARKETDATA 199
#define T_SUBSCRIBEFORQUOTERSP 200
#define T_UNSUBSCRIBEFORQUOTERSP 201
#define T_ONRSPSUBMARKETDATA 202
#define T_ONRSPUNSUBMARKETDATA 203
#define T_ONRSPSUBFORQUOTERSP 204
#define T_ONRSPUNSUBFORQUOTERSP 205
#define T_ONRTNDEPTHMARKETDATA 206

struct UVConnectField {
  char front_addr[200];
  char szPath[50];
  int public_topic_type;
  int private_topic_type;
};

struct LookupCtpApiBaton {
  uv_work_t work;
  void(*callback)(int, void*);
  void* uv_trader_obj;
  void* uv_market_obj;
  void* args;
  int fun;
  int iRequestID;
  int nResult;
  int uuid;//回调标识
  int nCount;
};

struct CbRtnField {
  uv_work_t work;
  int eFlag;//事件标识
  int nRequestID;
  int nReason;
  int nTimeLapse;
  void* rtnField;
  void* rspInfo;
  bool bIsLast;
};

struct CbWrap {
  void(*callback)(CbRtnField *data);
};

struct ptrCmp
{
  bool operator()( std::string s1, std::string s2 ) const
  {
    // return strcmp( s1, s2 ) < 0;
    return s1 == s2;
  }
};

#endif
